'use strict';
const paths={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',book:'<path d="M12 5C8 3 5 3 2 4v15c4-1 7 0 10 2 3-2 6-3 10-2V4c-3-1-6-1-10 1v16"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9S4 17 4 12V6z"/><path d="m8 12 3 3 5-6"/>',pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',circle:'<path d="M20 8a9 9 0 1 0 1 7M20 3v5h-5"/><path d="M9 9h6v6H9z"/>',route:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M7 5h9a4 4 0 0 1 0 8H8a3 3 0 0 0 0 6h9"/>',hotel:'<path d="M5 21V3h14v18M3 21h18M9 7h1m4 0h1M9 11h1m4 0h1M10 21v-5h4v5"/>',link:'<path d="m10 14 4-4M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 2 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0" transform="translate(1 -1)"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',check:'<path d="m5 12 4 4L19 6"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.book}</svg>`;
const navigation=[['anasayfa','Yolculuk rehberim','home'],['umre','Umre takibi','route'],['tavaf','Fazladan tavaf','circle'],['raporlar','İbadet raporlarım','book'],['dualar','Dualar','book'],['mikat','Mikat sınırları','pin'],['ihram','İhram yasakları','shield'],['mekke','Ziyaret yerleri','globe'],['harita','Ziyaret haritası','pin'],['ziyaret-raporu','Ziyaret raporum','check'],['otel','Otel bilgilerim','hotel'],['baglantilar','Faydalı bağlantılar','link'],['kuran','Kur’an oku','book','https://salihcanoz.github.io/kk/i.html']];
const sourceDiyanet='https://www2.diyanet.gov.tr/DiniYay%C4%B1nlarGenelMudurlugu/WebKutuphanesi/Kaynak%20Eserler/hac_ilmihali.pdf';
const sourceIhram='https://islamansiklopedisi.org.tr/ihram';
const external=(url,label,cls='')=>`<a class="${cls}" href="${url}" target="_blank" rel="noopener noreferrer">${label}<span class="sr-only"> (yeni sekmede açılır)</span></a>`;
const source=(url=sourceDiyanet,label='Diyanet · Hac İlmihali')=>external(url,`Kaynak: ${label} ↗`,'source');
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('main');
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),4000);}
function intro(title,description){return `<div class="page-intro"><div>${title?`<h1>${title}</h1>`:''}<p>${description}</p></div><span class="date-tag">Hac & Umre</span></div>`;}
function render(){disposeVisitMap();const rawRoute=location.hash.slice(1)||'anasayfa';const route=rawRoute==='say'?'umre':rawRoute;document.querySelector('#nav').innerHTML=navigation.map(([id,label,ic,url],i)=>`${id==='otel'?'<div class="nav-break"></div>':''}<a href="${url||'#'+id}" ${url?'target="_blank" rel="noopener noreferrer" aria-label="Kur’an oku (yeni sekmede açılır)"':''} class="nav-link ${route===id||(id==='mekke'&&route==='medine')?'active':''}" ${route===id||(id==='mekke'&&route==='medine')?'aria-current="page"':''}>${icon(ic)}${label}${url?' ↗':''}</a>`).join('');document.querySelector('#breadcrumb').textContent=navigation.find(n=>n[0]===route)?.[1]||(route==='medine'?'Ziyaret yerleri':'Kaynaklar');try{main.innerHTML=route==='anasayfa'?home():detail(route);}catch(error){console.error(error);main.innerHTML=intro('Bu bölüm açılamadı','Kayıtlı bilgilerinizden biri okunamadı. Sayfayı yeniden açın; sorun sürerse tarayıcınızın depolama iznini kontrol edin.');}if(route==='harita')initVisitMap();document.title=t(route==='anasayfa'?'Hac ve Umre Rehberi':navigation.find(n=>n[0]===route)?.[1]||(route==='medine'?'Ziyaret yerleri':'Kaynaklar'))+' · Sefer';document.querySelector('#sidebar').classList.remove('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded','false');document.querySelector('#sidebar').inert=window.matchMedia('(max-width:700px)').matches;localizePage();}

document.querySelector('#menu-toggle').addEventListener('click',()=>{const open=document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded',String(open));document.querySelector('#sidebar').inert=!open;});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);main.focus({preventScroll:true});});
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();main.focus();main.scrollIntoView();});
window.matchMedia('(max-width:700px)').addEventListener('change',event=>{document.querySelector('#sidebar').inert=event.matches&&!document.querySelector('#sidebar').classList.contains('open');});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.querySelector('#sidebar').classList.contains('open')){document.querySelector('#sidebar').classList.remove('open');document.querySelector('#sidebar').inert=window.matchMedia('(max-width:700px)').matches;document.querySelector('#menu-toggle').setAttribute('aria-expanded','false');document.querySelector('#menu-toggle').focus();}});
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'open_guide_section',title:'Rehber bölümü aç',description:'Sefer rehberinin seçilen bölümünü açar. Otel kayıtlarını değiştirmez.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['anasayfa','ihram','mikat','dualar','tavaf','say','mekke','medine','otel','baglantilar','kaynaklar','raporlar','ziyaret-raporu','umre','harita']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(key=>key!=='section')||!['anasayfa','ihram','mikat','dualar','tavaf','say','mekke','medine','otel','baglantilar','kaynaklar','raporlar','ziyaret-raporu','umre','harita'].includes(input.section))throw new Error('Geçersiz rehber bölümü');location.hash=input.section;render();window.scrollTo(0,0);return {section:input.section,title:document.title};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

// Dutch visitors wait for the dictionary so the first paint is already translated.
(language==='nl'?loadDictionary():Promise.resolve(true)).then(loaded=>{if(!loaded)language='tr';render();if(storageError)toast('Kayıtlı bilgiler okunamadı. Otel bilgilerinizi yeniden ekleyebilirsiniz.');});
// Offline support: the service worker keeps the guide, prayers and your visited photos available without a connection.
if('serviceWorker' in navigator&&/^https?:$/.test(location.protocol))window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
