'use strict';
// Hotel records and the hotel dialog, including the optional "use my location" flow.
let draftLocation=null;let locationRequest=0;
function validLocation(value){return !!value&&Number.isFinite(value.latitude)&&Math.abs(value.latitude)<=90&&Number.isFinite(value.longitude)&&Math.abs(value.longitude)<=180&&Number.isFinite(value.accuracy)&&value.accuracy>=0;}
let hotels={mekke:null,medine:null};let storageError=false;
try{const saved=JSON.parse(localStorage.getItem('sefer.hotels.v1')||'{}');for(const city of ['mekke','medine']){const h=saved?.[city];if(h&&typeof h.name==='string'&&typeof h.address==='string')hotels[city]={name:h.name.slice(0,120),address:h.address.slice(0,600),note:typeof h.note==='string'?h.note.slice(0,300):'',location:validLocation(h.location)?{latitude:h.location.latitude,longitude:h.location.longitude,accuracy:h.location.accuracy}:null};}}catch{storageError=true;}
function hotelMapUrl(h,city){return h.location?'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(h.location.latitude+','+h.location.longitude):'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(h.name+' '+h.address+' '+(city==='mekke'?'Makkah':'Madinah'));}
function hotelSummary(city){const h=hotels[city];if(!h)return '';return `<div class="saved-hotel"><div class="hotel-city-label">${city==='mekke'?'Mekke':'Medine'}</div><h3 data-no-translate>${escapeHTML(h.name)}</h3><p class="muted" data-no-translate>${escapeHTML(h.address)}</p>${h.location?`<p class="muted">⌖ Konum kayıtlı · yaklaşık ±${Math.ceil(h.location.accuracy)} m</p>`:''}${h.note?`<p data-no-translate>${escapeHTML(h.note)}</p>`:''}<div class="actions">${external(hotelMapUrl(h,city),`${icon('pin')} Yol tarifi`,'button')}<button class="button" data-edit="${city}">Düzenle</button></div></div>`;}
function hotelPanel(){return `<section class="panel"><div class="panel-title">${icon('hotel')}<h2>Otelim nerede?</h2></div>${hotels.mekke||hotels.medine?hotelSummary('mekke')+hotelSummary('medine')+'<a class="source" href="#otel">Tüm otel bilgilerim →</a>':`<div class="hotel-empty"><div class="hotel-symbol">${icon('hotel')}</div><h3>Oteliniz elinizin altında olsun</h3><p>Adresinizi bir kez kaydedin,<br>ihtiyacınız olduğunda kolayca ulaşın.</p><button class="button primary full" data-edit="mekke">+ Otel bilgisi ekle</button></div>`}<div class="storage-note">${icon('check')} Yalnızca bu cihazda saklanır</div></section>`;}

document.addEventListener('click',event=>{const remove=event.target.closest('[data-delete]');if(remove&&confirm(t('Bu şehre ait otel bilgisi silinsin mi?'))){const next={...hotels,[remove.dataset.delete]:null};try{localStorage.setItem('sefer.hotels.v1',JSON.stringify(next));hotels=next;render();toast('Otel bilgisi silindi.');}catch{toast('Bilgi silinemedi. Tarayıcı depolama iznini kontrol edin.');}}const edit=event.target.closest('[data-edit]');if(edit)openHotel(edit.dataset.edit);});
function openHotel(city){const form=document.querySelector('#hotel-form');form.reset();form.elements.city.value=city;loadHotelFields(city);document.querySelector('#form-error').textContent='';document.querySelector('#hotel-dialog').showModal();}
function loadHotelFields(city){cancelLocationRequest();const h=hotels[city];draftLocation=h?.location?{...h.location}:null;showLocation();for(const field of ['name','address','note'])document.querySelector('#hotel-'+field).value=h?.[field]||'';}
document.querySelector('#hotel-city').addEventListener('change',e=>loadHotelFields(e.target.value));
document.querySelector('#close-dialog').addEventListener('click',()=>document.querySelector('#hotel-dialog').close());
document.querySelector('#hotel-form').addEventListener('submit',e=>{e.preventDefault();const form=e.target;const city=form.elements.city.value;const hotel={name:form.elements.name.value.trim(),address:form.elements.address.value.trim(),note:form.elements.note.value.trim(),location:draftLocation?{...draftLocation}:null};if(!hotel.name||(!hotel.address&&!hotel.location)){document.querySelector('#form-error').textContent='Lütfen otel adını yazın ve adres veya güncel konum ekleyin.';return;}try{localStorage.setItem('sefer.hotels.v1',JSON.stringify({...hotels,[city]:hotel}));hotels[city]=hotel;document.querySelector('#hotel-dialog').close();render();toast('Otel bilgileriniz bu cihaza kaydedildi.');}catch{document.querySelector('#form-error').textContent='Bilgiler kaydedilemedi. Tarayıcınızın yerel depolama iznini kontrol edin.';}});

function cancelLocationRequest(){locationRequest++;const button=document.querySelector('#use-location');button.disabled=false;button.textContent='⌖ Güncel konumumu kullan';button.removeAttribute('aria-busy');}
function showLocation(message){document.querySelector('#remove-location').hidden=!draftLocation;document.querySelector('#location-status').textContent=message??(draftLocation?`Konum seçildi: ${draftLocation.latitude.toFixed(6)}, ${draftLocation.longitude.toFixed(6)} · yaklaşık ±${Math.ceil(draftLocation.accuracy)} m. ${draftLocation.accuracy>100?'Konum hassasiyeti düşük; yeniden deneyebilir veya açık adres yazabilirsiniz. ':''}Kaydet düğmesiyle onaylayın.`:'');}
document.querySelector('#hotel-dialog').addEventListener('close',()=>{cancelLocationRequest();draftLocation=null;showLocation();});
document.querySelector('#remove-location').addEventListener('click',()=>{cancelLocationRequest();draftLocation=null;showLocation('Konum kaldırıldı. Otel adresini yazarak devam edebilirsiniz.');});
document.querySelector('#use-location').addEventListener('click',()=>{
 cancelLocationRequest();
 if(!window.isSecureContext){showLocation('Konum için siteyi HTTPS üzerinden açın. Adresi elle de yazabilirsiniz.');return;}
 if(!navigator.geolocation){showLocation('Bu tarayıcı konum özelliğini desteklemiyor. Otel adresini elle yazabilirsiniz.');return;}
 const request=locationRequest;const button=document.querySelector('#use-location');button.disabled=true;button.textContent='Konum alınıyor…';button.setAttribute('aria-busy','true');showLocation('Konum izni isteniyor. Lütfen tarayıcınızdaki isteği yanıtlayın.');
 const current=()=>request===locationRequest&&document.querySelector('#hotel-dialog').open;
 const failure=error=>{if(!current())return;cancelLocationRequest();const messages={1:'Konum izni verilmedi. Tarayıcı ayarlarından izin verebilir veya otel adresini elle yazabilirsiniz.',2:'Konum belirlenemedi. Konum servislerini kontrol edip yeniden deneyin veya adresi elle yazın.',3:'Konum isteği zaman aşımına uğradı. Yeniden deneyin veya adresi elle yazın.'};showLocation((messages[error?.code]||'Konum alınamadı. Adresi elle yazabilirsiniz.')+(draftLocation?' Önceki seçili konum korundu.':''));};
 try{navigator.geolocation.getCurrentPosition(position=>{if(!current())return;const location={latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy};if(!validLocation(location)){failure({code:2});return;}cancelLocationRequest();draftLocation=location;showLocation();},failure,{enableHighAccuracy:true,timeout:15000,maximumAge:0});}catch{failure({code:2});}
});
