'use strict';
// Prayer library: search, category filter and the Arabic / reading / meaning views.
const prayerCategories={ihram:'İhram ve niyet',tavaf:'Tavaf ve Mekke',say:'Sa‘y',medine:'Medine ve ziyaret'};
function prayerItems(route){return (window.SEFER_PRAYERS||[]).filter(item=>route==='dualar'||item.category===route);}
let prayerView='arabic';
try{const saved=localStorage.getItem('sefer.prayerView.v1');if(['arabic','transliteration','meaning'].includes(saved))prayerView=saved;}catch{}
function prayerEntry(item){
 const paragraphs=text=>text.split(/\n+/).filter(Boolean).map(p=>`<p>${escapeHTML(p)}</p>`).join('');
 const views=item.arabic?[['arabic','Arapça metin'],['transliteration','Türk harfleriyle okunuş'],['meaning','Türkçe anlam']]:[['meaning','Türkçe niyet']];
 const selected=item.arabic?prayerView:'meaning';
 const panels=views.map(([key,label])=>`<section id="${item.id}-${key}" class="prayer-reading-panel" data-prayer-panel="${key}" ${key===selected?'':'hidden'}><h3 class="prayer-label">${label}</h3>${key==='transliteration'?'<p class="reading-note">Türk harfleri Arapçadaki bütün sesleri tam karşılamaz; bu okunuş yardımcıdır.</p>':''}${key==='meaning'&&item.arabic?'<p class="reading-note">Arapça metinden açıklayıcı Türkçe çeviri.</p>':''}<div class="${key==='arabic'?'arabic prayer-full-text':'prayer-turkish-text'}" lang="${key==='arabic'?'ar':key==='transliteration'&&language==='nl'?'nl':'tr'}" dir="${key==='arabic'?'rtl':'ltr'}">${paragraphs(key==='transliteration'&&language==='nl'?(window.SEFER_PRONUNCIATION_NL[item.id]||''):item[key]||item.intention||'')}</div></section>`).join('');
 const controls=item.arabic?`<div class="prayer-view-buttons" role="group" aria-label="Dua görünümü">${views.map(([key,label])=>`<button type="button" data-prayer-view="${key}" aria-pressed="${selected===key}" aria-controls="${item.id}-${key}">${label}</button>`).join('')}</div>`:'';
 const audio=item.audio.map(a=>`<div class="prayer-audio"><label>${a.language==='arabic'?'Arapça ses':'Türkçe ses'}<audio controls preload="none" src="${escapeHTML(a.url)}">Ses kaydını dinlemek için kaynak bağlantısını açabilirsiniz.</audio></label></div>`).join('');
 return `<details class="content-panel prayer-entry" id="${item.id}"><summary><span><span class="prayer-category">${prayerCategories[item.category]}</span><span class="prayer-title">${escapeHTML(item.title)}</span></span><span class="prayer-expand" aria-hidden="true">+</span></summary><div class="prayer-entry-body">${controls}${panels}${!item.arabic?'<p class="reading-note">Bu niyet kaynakta Türkçe verilmiştir; ayrıca Arapça metin veya okunuş bulunmaz.</p>':''}${audio}<div class="prayer-source-actions">${external(item.source,'Diyanet · Arapça kaynak ve açıklama ↗','button')}</div></div></details>`;
}
document.addEventListener('click',event=>{const button=event.target.closest('[data-prayer-view]');if(!button)return;const view=button.dataset.prayerView;if(!['arabic','transliteration','meaning'].includes(view))return;prayerView=view;try{localStorage.setItem('sefer.prayerView.v1',view);}catch{}document.querySelectorAll('.prayer-entry').forEach(entry=>{if(!entry.querySelector('[data-prayer-view]'))return;entry.querySelectorAll('[data-prayer-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.prayerView===view)));entry.querySelectorAll('[data-prayer-panel]').forEach(panel=>panel.hidden=panel.dataset.prayerPanel!==view);});});

function prayerLibrary(route){
 const items=prayerItems(route),title=route==='tavaf'?'Tavaf duaları':route==='say'?'Sa‘y duaları':'Dualar';
 return intro(title,'Diyanet kaynaklı Arapça dualar; Türkçe anlamları ve okunuş yardımı.')+`<div class="tab-buttons prayer-tabs" aria-label="İbadet takibi ve dualar"><a href="#dualar" ${route==='dualar'?'class="selected" aria-current="page"':''}>Dualar</a><a href="#tavaf" ${route==='tavaf'?'class="selected" aria-current="page"':''}>Fazladan tavaf</a><a href="#umre" ${route==='say'?'class="selected" aria-current="page"':''}>Umre takibi</a></div><div class="info-banner">Şavt başlıkları okumayı kolaylaştırmak içindir; her şavtta belirli bir dua okumak zorunlu değildir. Kendi dilinizle de dua edebilirsiniz.</div><div class="prayer-tools"><label>Dua ara<input id="prayer-search" type="search" placeholder="Örn. zemzem, telbiye, Merve" aria-controls="prayer-results"></label>${route==='dualar'?`<label>Bölüm<select id="prayer-category" aria-controls="prayer-results"><option value="all">Tüm bölümler</option>${Object.entries(prayerCategories).map(([key,value])=>`<option value="${key}">${value}</option>`).join('')}</select></label>`:''}</div><p class="reading-note">Bir duayı açıp Arapça metin, Türk harfleriyle okunuş veya Türkçe anlamı seçin. Seçiminiz sonraki şavtlarda da korunur. Ses kayıtları internet gerektirir.</p><p class="prayer-result-count" id="prayer-result-count" role="status">${items.length} dua ve niyet</p><div id="prayer-results" data-route="${route}">${items.map(prayerEntry).join('')}</div>${source('https://hacumreegitim.hac.gov.tr/dualar','Diyanet · Hac ve Umre Duaları')}`;
}
function filterPrayerLibrary(){const results=document.querySelector('#prayer-results');if(!results)return;const normalize=text=>text.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[’‘'ʿ]/g,'');const term=normalize(document.querySelector('#prayer-search').value.trim());const category=document.querySelector('#prayer-category')?.value||'all';const items=prayerItems(results.dataset.route).filter(item=>(category==='all'||item.category===category)&&normalize(item.title+' '+t(item.title)+' '+prayerCategories[item.category]+' '+t(prayerCategories[item.category])).includes(term));results.innerHTML=items.length?items.map(prayerEntry).join(''):'<div class="content-panel"><p>Bu aramayla eşleşen dua bulunamadı. Aramayı kısaltabilir veya bölüm seçimini değiştirebilirsiniz.</p></div>';document.querySelector('#prayer-result-count').textContent=items.length+' dua ve niyet';}
document.addEventListener('input',event=>{if(event.target.id==='prayer-search')filterPrayerLibrary();});
document.addEventListener('change',event=>{if(event.target.id==='prayer-category')filterPrayerLibrary();});
