function tMiqat(value){return miqatOptions.includes(value)?t(value):value;}
const ritualKey='sefer.rituals.v1';
const miqatOptions=['Zülhuleyfe (Âbâr-ı Ali)','Cuhfe / Râbiğ','Karnülmenâzil (Seylülkebîr)','Yelemlem','Zâtüırk','Ten‘îm (Hil bölgesi)','Ci‘râne (Hil bölgesi)','Belirtilmedi'];
const ritualName=type=>type==='umre'?'Umre':type==='tavaf'?'Tavaf':'Sa‘y';
function readRituals(){const raw=localStorage.getItem(ritualKey);if(!raw)return {active:{},history:[]};const data=JSON.parse(raw);if(!data||!data.active||!Array.isArray(data.history))throw Error('Kayıt okunamadı');return data;}
function durationText(ms){const sec=Math.max(0,Math.floor(ms/1000));return [Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(n=>String(n).padStart(2,'0')).join(':');}
function ritualDate(time){return new Intl.DateTimeFormat(uiLocale(),{timeZone:'Asia/Riyadh',dateStyle:'long',timeStyle:'short'}).format(new Date(time));}
function ritualSave(data){try{localStorage.setItem(ritualKey,JSON.stringify(data));return true;}catch{toast('Kayıt saklanamadı. Depolama iznini veya boş alanı kontrol edin; bulunduğunuz şavt değiştirilmedi.');return false;}}
function ritualLinks(){return '<div class="tracker-links"><a class="button" href="#umre">Umre takibi</a><a class="button" href="#tavaf">Bağımsız tavaf</a><a class="button" href="#raporlar">İbadet raporlarım</a><a class="button" href="#dualar">Dualar</a></div>';}
function umreStages(stage){return `<ol class="umre-stages" aria-label="Umre takibinin aşamaları"><li class="${stage==='tavaf'?'current':'done'}">${stage==='tavaf'?'1.':'✓'} Tavaf · 7 şavt</li><li class="${stage==='say'?'current':''}">2. Sa‘y · 7 şavt</li></ol>`;}
function ritualCancel(mode,s){return `<details class="content-panel"><summary>Bu takibi iptal et</summary><p>Devam eden takip kaldırılır. Tamamlanmış tavaf ve önceki raporlar korunur.</p><button class="button" data-ritual-action="cancel" data-mode="${mode}" data-session="${s.id}">Evet, bu takibi iptal et</button></details>`;}
function trackerPage(mode){
 mode=mode==='say'?'umre':mode;
 let data;try{data=readRituals();}catch{return intro('Kayıtlarınıza ulaşılamıyor','Tarayıcınızın depolama iznini kontrol edip sayfayı yeniden açın.');}
 const umre=mode==='umre',session=data.active[mode];
 const top=intro(umre?'Umre takibi':'Bağımsız tavaf',umre?'Umre tavafını ve ardından sa‘yini aynı kayıt içinde takip edin.':'Umre dışında yaptığınız tavafı 7 şavt boyunca takip edin.')+ritualLinks();
 if(!session)return top+(umre?umreStages('tavaf'):'')+`<section class="content-panel tracker-setup"><h2>${umre?'Umre tavafına başla':'Tavafa başla'}</h2><form id="ritual-start" data-mode="${mode}">${umre?`<label for="ritual-miqat">İhrama girdiğiniz yer (mikat)</label><select id="ritual-miqat" name="miqat" required><option value="">Bir seçenek seçin</option>${miqatOptions.map(label=>`<option value="${escapeHTML(label)}">${escapeHTML(label)}</option>`).join('')}<option value="other">Diğer</option></select><div id="ritual-other-wrap" hidden><label for="ritual-other">İhrama girdiğiniz yer</label><input id="ritual-other" name="other" maxlength="120"></div><p class="reading-note">Mikat, umre kaydınıza eklenir. Süre, tavafı başlattığınız anda ölçülür. Tavaf bitmeden sa‘y başlatılamaz.</p>`:'<p>Bu kayıt yalnızca tavaf içindir; ardından sa‘y başlatılmaz. Mikat seçmeniz gerekmez.</p>'}<button class="button primary" type="submit">${umre?'Umre tavafını başlat':'Bağımsız tavafı başlat'}</button></form></section>${umre?'<p class="reading-note">Bu ekran tavaf ve sa‘y aşamalarını takip eder. İhrama giriş ve sa‘yden sonra tıraş olup ihramdan çıkış da umre uygulamasının parçalarıdır.</p>':''}<div class="info-banner">Her şavta özel bir dua okumak zorunlu değildir.</div>`;
 if(umre&&session.stage==='between')return top+umreStages('between')+`<section class="content-panel tracker-setup"><span class="pill">Tavaf · 7 / 7 tamamlandı</span><h2>Sa‘y için hazır olduğunuzda devam edin</h2><p>Tavaf süresi: <strong>${durationText(session.tavaf.endedAt-session.tavaf.startedAt)}</strong></p><p>Mikat: <span data-no-translate>${escapeHTML(tMiqat(session.miqat))}</span></p><p>Sa‘y Safa’da başlar. Safa → Merve birinci, Merve → Safa ikinci şavttır; yedinci şavt Merve’de biter.</p><p class="reading-note">Tavaf namazınızı kıldıktan sonra sa‘y için Safa’ya geçin. Sa‘y süresi aşağıdaki düğmeye bastığınızda başlar; aradaki süre raporda ayrı gösterilir.</p><button class="button primary" data-ritual-action="begin-say" data-mode="umre" data-session="${session.id}">Bu umrenin sa‘yini başlat</button></section>`+ritualCancel(mode,session);
 const type=umre?session.stage:'tavaf',part=umre?session[type]:session;
 if(!part||!['tavaf','say'].includes(type))return top+'<p>Takip kaydı okunamadı. İbadet raporlarınızı kontrol edin.</p>';
 const step=part.completed.length+1,prayer=(window.SEFER_PRAYERS||[]).find(p=>p.id==='dua-'+((type==='tavaf'?23:43)+step));
 const lastLabel=umre&&type==='tavaf'?'7. şavtı tamamla · sa‘y aşamasına geç':'7. şavtı tamamla ve raporu gör';
 return top+(umre?umreStages(type):'')+`<section class="content-panel tracker-active"><div class="tracker-heading"><div><span class="prayer-category">${umre?'UMRE · ':''}${type==='tavaf'?'TAVAF':'SA‘Y'}</span><h2 tabindex="-1" id="current-shavt">${step}. şavt <span>/ 7</span></h2><p>${type==='say'?(step%2?'Safa → Merve':'Merve → Safa'):'Kâbe çevresindeki '+step+'. tur'}</p></div><div class="tracker-clock"><span>${ritualName(type)} süresi</span><strong data-ritual-clock="${part.startedAt}">${durationText(Date.now()-part.startedAt)}</strong></div></div><ol class="shavt-steps" aria-label="Şavt ilerlemesi">${Array.from({length:7},(_,i)=>`<li class="${i+1<step?'done':i+1===step?'current':''}" ${i+1===step?'aria-current="step"':''}><span aria-hidden="true">${i+1<step?'✓':i+1}</span><span class="sr-only">${i+1}. şavt${i+1<step?' tamamlandı':i+1===step?' devam ediyor':''}</span></li>`).join('')}</ol><p class="reading-note">${umre?'Mikat: '+'<span data-no-translate>'+escapeHTML(tMiqat(session.miqat))+'</span> · ':''}${part.completed.length} şavt tamamlandı</p><div class="tracker-action"><button class="button primary" data-ritual-action="next" data-mode="${mode}" data-stage="${type}" data-session="${session.id}" data-step="${step}">${step===7?lastLabel:step+'. şavtı tamamla → '+(step+1)+'. şavta geç'}</button></div></section><p class="reading-note">Şavt geçişi sizin onayınızla yapılır. Sayfayı kapatsanız da süre işlemeye devam eder.</p><h2 class="tracker-prayer-title">Bu şavtta okunabilecek dua</h2>${prayer?prayerEntry(prayer).replace('<details ','<details open '):'<p>Dua metni yüklenemedi. Dualar bölümünü açabilirsiniz.</p>'}<p class="reading-note">Her şavta özel bir dua okumak zorunlu değildir; kendi dilinizle de dua edebilirsiniz.</p>`+ritualCancel(mode,session);
}
function ritualPartReport(part,label){return `<details><summary>${label} · ${durationText(part.endedAt-part.startedAt)} · Şavt süreleri</summary><p>${ritualDate(part.startedAt)} → ${ritualDate(part.endedAt)}</p><ol>${part.completed.map((t,i)=>`<li>${i+1}. şavt: ${durationText(t-(i?part.completed[i-1]:part.startedAt))}</li>`).join('')}</ol></details>`;}
function ritualReportCard(r){const umre=r.type==='umre';const title=umre?'Umre · tavaf ve sa‘y':r.purpose==='independent'?'Bağımsız tavaf':r.purpose==='umre-incomplete'?'Umre tavafı · takip durduruldu':ritualName(r.type)+' · önceki kayıt';return `<section class="content-panel ritual-report"><div class="tracker-heading"><h2>${title}</h2><span class="pill">${umre?'Tavaf 7/7 · Sa‘y 7/7':'7 / 7 şavt'}</span></div><dl><div><dt>Başlangıç tarihi ve saati</dt><dd>${ritualDate(r.startedAt)}</dd></div><div><dt>Bitiş tarihi ve saati</dt><dd>${ritualDate(r.endedAt)}</dd></div>${r.miqat?`<div><dt>İhrama girilen yer (mikat)</dt><dd data-no-translate>${escapeHTML(tMiqat(r.miqat))}</dd></div>`:''}<div><dt>Toplam takip süresi</dt><dd>${durationText(r.endedAt-r.startedAt)}</dd></div>${umre?`<div><dt>Tavaf süresi</dt><dd>${durationText(r.tavaf.endedAt-r.tavaf.startedAt)}</dd></div><div><dt>Tavaf ile sa‘y arası</dt><dd>${durationText(r.say.startedAt-r.tavaf.endedAt)}</dd></div><div><dt>Sa‘y süresi</dt><dd>${durationText(r.say.endedAt-r.say.startedAt)}</dd></div>`:''}</dl>${umre?ritualPartReport(r.tavaf,'Tavaf')+ritualPartReport(r.say,'Sa‘y')+'<p class="reading-note">Tavaf ve sa‘y kaydedildi. Umrede sa‘yden sonra tıraş olup ihramdan çıkılır; bu işlem sayaçla takip edilmez. <a class="source" href="https://hacumreegitim.hac.gov.tr/fetvalar" target="_blank" rel="noopener noreferrer">Diyanet · Umre uygulaması ↗</a></p>':ritualPartReport(r,ritualName(r.type))}</section>`;}
function ritualReports(){let data;try{data=readRituals();}catch{return intro('Raporlar okunamadı','Tarayıcınızın depolama iznini kontrol edin.');}const umre=data.history.filter(r=>r.type==='umre').length,independent=data.history.filter(r=>r.purpose==='independent').length,other=data.history.length-umre-independent;return intro('İbadet raporlarım','Umre tavafı ve sa‘yi birlikte; bağımsız tavaflar ayrı kayıt olarak gösterilir.')+ritualLinks()+`<p class="report-summary">${umre} umre takibi · ${independent} bağımsız tavaf${other?' · '+other+' diğer kayıt':''}</p>${data.active.umre?`<section class="content-panel"><h2>Devam eden umre</h2><p>${data.active.umre.stage==='between'?'Tavaf tamamlandı; sa‘y bekleniyor.':data.active.umre.stage==='say'?'Tavaf tamamlandı; sa‘y devam ediyor.':'Tavaf devam ediyor.'}</p><a class="button primary" href="#umre">Takibe devam et</a></section>`:''}${data.active.tavaf?'<section class="content-panel"><h2>Devam eden tavaf</h2><a class="button" href="#tavaf">Takibe devam et</a></section>':''}${data.active.say?`<section class="content-panel"><h2>Önceki sa‘y kaydı · tamamlanmamış</h2><p>${data.active.say.completed.length} / 7 şavt · ${ritualDate(data.active.say.startedAt)}</p><p>Mikat: <span data-no-translate>${escapeHTML(tMiqat(data.active.say.miqat||'Belirtilmedi'))}</span></p><p class="reading-note">Bu kayıt korunuyor. Bağlı bir umre tavafı bulunmadığı için yeni umre takibine otomatik eklenmedi.</p></section>`:''}${data.history.length?data.history.slice().sort((a,b)=>b.endedAt-a.endedAt).map(ritualReportCard).join(''):'<section class="content-panel"><h2>Henüz tamamlanmış kayıt yok</h2><p>Umrenin tavaf ve sa‘y aşamalarını veya bağımsız tavafın 7 şavtını tamamladığınızda raporunuz burada oluşur.</p></section>'}<p class="reading-note">Önceki ayrı tavaf ve sa‘y kayıtları, hangi umreye ait oldukları bilinmediği için birleştirilmeden korunur. Saatler Mekke ve Medine yerel saatine göredir (UTC+3). Toplam süre araları da içerir. Kayıtlar yalnızca bu tarayıcıda saklanır; tarayıcı verilerini temizlemek kayıtları siler.</p>`;}
document.addEventListener('change',event=>{if(event.target.id==='ritual-miqat'){const other=event.target.value==='other';document.querySelector('#ritual-other-wrap').hidden=!other;document.querySelector('#ritual-other').required=other;}});
document.addEventListener('submit',event=>{if(event.target.id!=='ritual-start')return;event.preventDefault();const form=event.target,mode=form.dataset.mode;if(!['umre','tavaf'].includes(mode))return;let miqat=null;if(mode==='umre'){miqat=form.elements.miqat.value;if(miqat==='other')miqat=form.elements.other.value.trim();if(!miqat||miqat==='İhram gerektirmeyen tavaf'){toast('Lütfen ihrama girdiğiniz yeri seçin veya yazın.');return;}}try{const data=readRituals();if(data.active[mode]){render();return;}const now=Date.now(),base={id:crypto.randomUUID(),type:mode,miqat,startedAt:now};data.active[mode]=mode==='umre'?{...base,stage:'tavaf',tavaf:{startedAt:now,completed:[]},say:null}:{...base,purpose:'independent',completed:[]};if(ritualSave(data)){render();document.querySelector('#current-shavt')?.focus();}}catch{toast('Takip başlatılamadı. Tarayıcının depolama iznini kontrol edin.');}});
let lastRitualTap=0;
document.addEventListener('click',event=>{const button=event.target.closest('[data-ritual-action]');if(!button)return;const {mode,session:id,ritualAction:action}=button.dataset;if(!['umre','tavaf'].includes(mode))return;try{const data=readRituals(),s=data.active[mode];if(!s||s.id!==id){render();return;}let finished=false;const now=Date.now();if(action==='cancel'){if(mode==='umre'&&s.tavaf.endedAt){data.history.push({id:s.id+'-tavaf',type:'tavaf',purpose:'umre-incomplete',miqat:s.miqat,...s.tavaf});}delete data.active[mode];}else if(action==='begin-say'){if(mode!=='umre'||s.stage!=='between'||s.tavaf.completed.length!==7||!s.tavaf.endedAt)return;s.say={startedAt:Math.max(now,s.tavaf.endedAt),completed:[]};s.stage='say';}else if(action==='next'){const type=mode==='umre'?s.stage:'tavaf',part=mode==='umre'?s[type]:s,step=Number(button.dataset.step);if(!part||!['tavaf','say'].includes(type)||button.dataset.stage!==type||part.completed.length!==step-1||step<1||step>7||now-lastRitualTap<900)return;const timestamp=Math.max(now,part.startedAt,...part.completed);part.completed.push(timestamp);if(step===7){part.endedAt=timestamp;if(mode==='umre'&&type==='tavaf'){s.stage='between';}else{s.endedAt=timestamp;data.history.push(s);delete data.active[mode];finished=true;}}}else return;if(ritualSave(data)){lastRitualTap=now;if(finished){location.hash='raporlar';toast(mode==='umre'?'Umre tavafı ve sa‘yi tek rapora kaydedildi.':'Tavaf raporu kaydedildi.');}render();document.querySelector('#current-shavt')?.focus();window.scrollTo(0,0);}}catch{toast('Kayıt güncellenemedi. Sayfayı yeniden açıp tekrar deneyin.');}});
setInterval(()=>{document.querySelectorAll('[data-ritual-clock]').forEach(el=>{el.textContent=durationText(Date.now()-Number(el.dataset.ritualClock));});},1000);
window.addEventListener('storage',event=>{if(event.key===ritualKey&&['umre','tavaf','say','raporlar'].includes(location.hash.slice(1)))render();});
