let visitMap=null,visitMapLayer=null,mapCity='all',mapSearch='',mapStatus='all',mapMarkers={};
function disposeVisitMap(){if(visitMap){visitMap.remove();visitMap=null;visitMapLayer=null;}mapMarkers={};}
function visitMapPage(){return intro('Ziyaret haritası','Mekke, Medine ve çevresindeki tüm ziyaret yerlerini birlikte keşfedin.')+`<section class="content-panel map-controls"><label for="map-city">Şehir<select id="map-city"><option value="all">Tüm yerler</option><option value="mekke">Mekke ve çevresi</option><option value="medine">Medine ve çevresi</option></select></label><label for="map-search">Yer ara<input id="map-search" type="search" placeholder="Örn. Kuba, Huneyn, kuyusu" autocomplete="off"></label><label for="map-status">Ziyaret durumu<select id="map-status"><option value="all">Tümü</option><option value="visited">Ziyaret ettiklerim</option><option value="remaining">Henüz ziyaret etmediklerim</option></select></label><button class="button" id="map-fit">Seçili yerlerin tümünü göster</button></section><p id="map-count" role="status" class="reading-note"></p><div class="visit-map-layout"><div class="visit-map-panel"><div id="visit-map" aria-label="Ziyaret yerlerinin etkileşimli haritası"></div><p id="map-error" role="status" class="reading-note"></p><p class="map-legend"><span>🟢 Mekke ve çevresi</span><span>🟠 Medine ve çevresi</span><span>✓ Ziyaret edildi</span></p><p class="reading-note">İşaretler ziyaret noktalarını veya yaklaşık bölgeleri gösterir; giriş kapısı ya da yürüyüş rotası değildir. Aynı konumdaki yerler ortak işarette listelenir. Yaklaşık konumların açıklamasını kontrol edin.</p></div><div id="map-results" class="map-results" aria-label="Haritadaki yerler"></div></div><p class="reading-note">Harita internet gerektirir. Harita zemini OpenStreetMap’ten yüklenir; ziyaret kayıtlarınız bu tarayıcıda kalır. Konum kaynakları her işarette belirtilmiştir. Konum verileri: © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap katkıcıları (ODbL)</a>. <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener">Harita hatası bildir</a>.</p>`;}
function filteredMapPlaces(){const norm=s=>s.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[’‘'ʿ]/g,'');let records={};try{records=readVisits();}catch{}return allVisitPlaces().filter(p=>(mapCity==='all'||p.city===mapCity)&&norm(p.name+' '+p.type).includes(norm(mapSearch))&&(mapStatus==='all'||(mapStatus==='visited'?!!records[p.id]:!records[p.id]))).map(p=>({...p,visited:!!records[p.id],point:window.SEFER_MAP_POINTS[p.id]}));}
function mapPlaceInfo(p){return `<strong>${escapeHTML(p.name)}</strong><p>${p.visited?'✓ Ziyaret edildi · ':''}${escapeHTML(p.point.note)}</p>${external(p.point.source,'Konum kaynağı ↗')}<button class="button" data-map-detail="${p.id}">Ziyaret kartını aç</button> ${external('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.query),'Google Haritalar ↗')}`;}
function updateVisitMap(fit=true){if(!document.querySelector('#map-results'))return;const places=filteredMapPlaces();document.querySelector('#map-count').textContent=`${places.length} / ${allVisitPlaces().length} yer gösteriliyor · ${places.filter(p=>p.visited).length} ziyaret edildi`;
 document.querySelector('#map-results').innerHTML=places.length?places.map(p=>`<article class="map-result"><button class="map-place-button" data-map-focus="${p.id}"><span class="place-type">${p.city==='mekke'?'Mekke':'Medine'}${p.visited?' · ✓ Ziyaret edildi':''}</span><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.point.note)}</small><span>Haritada göster →</span></button><button class="text-button" data-map-detail="${p.id}">Ziyaret kartı</button></article>`).join(''):'<p class="content-panel">Bu filtrelerle eşleşen yer bulunamadı.</p>';
 if(!visitMap)return;visitMapLayer.clearLayers();mapMarkers={};const groups=new Map();for(const p of places){const key=p.point.lat+','+p.point.lng;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p);}for(const group of groups.values()){const p=group[0],done=group.every(x=>x.visited);const marker=L.marker([p.point.lat,p.point.lng],{title:group.map(x=>x.name).join(', '),icon:L.divIcon({className:'sefer-map-icon',html:`<span class="map-pin ${p.city} ${group.some(x=>x.point.approximate)?'approximate':''}">${group.length>1?group.length:done?'✓':'•'}</span>`,iconSize:[32,32],iconAnchor:[16,16]})}).bindPopup(group.map(mapPlaceInfo).join('<hr>'),{maxHeight:280,maxWidth:310}).addTo(visitMapLayer);for(const x of group)mapMarkers[x.id]=marker;}if(fit&&places.length)visitMap.fitBounds(places.map(p=>[p.point.lat,p.point.lng]),{padding:[35,35],maxZoom:14});}
function initVisitMap(){if(!document.querySelector('#visit-map'))return;document.querySelector('#map-city').value=mapCity;document.querySelector('#map-search').value=mapSearch;document.querySelector('#map-status').value=mapStatus;
 if(window.L){visitMap=L.map('visit-map',{scrollWheelZoom:false}).setView([23.0,39.7],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> katkıcıları'}).on('tileerror',()=>{const el=document.querySelector('#map-error');if(el)el.textContent='Harita zemini yüklenemedi. İnternet bağlantınızı kontrol edin; yer listesi ve Google Haritalar bağlantıları kullanılabilir.';}).addTo(visitMap);visitMapLayer=L.layerGroup().addTo(visitMap);}else document.querySelector('#map-error').textContent='Harita yüklenemedi. Aşağıdaki listeden ziyaret kartlarını açabilirsiniz.';updateVisitMap();}
document.addEventListener('input',e=>{if(e.target.id==='map-search'){mapSearch=e.target.value;updateVisitMap();}});
document.addEventListener('change',e=>{if(e.target.id==='map-city'){mapCity=e.target.value;updateVisitMap();}if(e.target.id==='map-status'){mapStatus=e.target.value;updateVisitMap();}});
document.addEventListener('click',e=>{if(e.target.closest('#map-fit'))updateVisitMap();const focus=e.target.closest('[data-map-focus]');if(focus){const marker=mapMarkers[focus.dataset.mapFocus];if(marker&&visitMap){visitMap.setView(marker.getLatLng(),window.SEFER_MAP_POINTS[focus.dataset.mapFocus].approximate?13:16);marker.openPopup();document.querySelector('#visit-map').scrollIntoView({behavior:'smooth',block:'center'});}}const detail=e.target.closest('[data-map-detail]');if(detail){const id=detail.dataset.mapDetail;location.hash=id.startsWith('mekke')?'mekke':'medine';setTimeout(()=>document.getElementById('place-'+id)?.scrollIntoView({behavior:'smooth',block:'center'}),100);}});
window.addEventListener('storage',e=>{if(e.key===visitStorageKey&&location.hash==='#harita')updateVisitMap(false);});
